# Optional Lab: Python, NumPy and Vectorization
A brief introduction to some of the scientific computing used in this course. In particular the NumPy scientific computing package and its use with python.

简单介绍在本课程中使用的一些科学计算方法。尤其是NumPy科学计算库和它的python编写

# Outline
- [&nbsp;&nbsp;1.1 Goals](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 Useful References](#toc_40015_1.2)
- [2 Python and NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 Vectors](#toc_40015_3)
- [&nbsp;&nbsp;3.1 Abstract](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy Arrays](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 Vector Creation](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 Operations on Vectors](#toc_40015_3.4)
- [4 Matrices](#toc_40015_4)
- [&nbsp;&nbsp;4.1 Abstract](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy Arrays](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 Matrix Creation](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 Operations on Matrices](#toc_40015_4.4)


In [1]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

<a name="toc_40015_1.1"></a>
## 1.1 Goals
In this lab, you will:
- Review the features of NumPy and Python that are used in Course 1

在这个lab中，你将：
- 复习在第一节学习的NumPy和Python功能

<a name="toc_40015_1.2"></a>
## 1.2 Useful References
- NumPy Documentation including a basic introduction: [NumPy.org](https://NumPy.org/doc/stable/)
- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)

- Numpy的手册，包含简单的介绍[NumPy.org](https://NumPy.org/doc/stable/)
- 具有挑战性的功能主题[NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)



<a name="toc_40015_2"></a>
# 2 Python and NumPy <a name='Python and NumPy'></a>
Python is the programming language we will be using in this course. It has a set of numeric data types and arithmetic operations. NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions. NumPy and python  work together fairly seamlessly. Python arithmetic operators work on NumPy data types and many NumPy functions will accept python data types.

Python是我们将会在本课程中使用的编程语言。该语言具有一系列数据类型和算数处理。NumPy是一个函数库，它拓展了Python的功能，添加了更加丰富的数据类型、向量、矩阵和很多矩阵函数。NumPy和Python简直是无缝结合。Python的算数操作可以直接应用于NumPy数据类型，许多NumPy函数也支持使用Python数据类型。


<a name="toc_40015_3"></a>
# 3 Vectors向量
<a name="toc_40015_3.1"></a>
## 3.1 Abstract摘要
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >Vectors, as you will use them in this course, are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as $\mathbf{x}$.  The elements of a vector are all the same type. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the *dimension* though mathematicians may prefer *rank*. The vector shown has a dimension of $n$. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science and these labs, indexing will typically run from 0 to n-1.  In notation, elements of a vector, when referenced individually will indicate the index in a subscript, for example, the $0^{th}$ element, of the vector $\mathbf{x}$ is $x_0$. Note, the x is not bold in this case.  

向量是数字的有序数组，你将在本课程中使用它。通常，向量使用加粗的小写字母表示，形如$\mathbf{x}$。向量内所有的元素类型必须一致。例如，向量不能同时包含字符型和数字。数组中元素的个数通常被称为**维数**，数学上也称为**秩**。图示就是一个$n$维向量。向量中的元素可以使用索引。在数学上，索引通常从1到n排序；而在计算机科学和本课程中，索引从0到n-1排序。习惯上，单独表示向量中的一个元素，可以用下标表示索引，例如，向量$\mathbf{x}$的第$0^{th}$个元素可以表示为$x_0$。注意x在这时没有加粗。

<a name="toc_40015_3.2"></a>
## 3.2 NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index. In Course 1, we will represent vectors as NumPy 1-D arrays. 

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]
 
 NumPy基础的数据结构是一个可以索引的n维**数组**，包含具有相同数据类型的(`dtype`)元素。你应该很快就注意到我们在这里重定义了**维数**。在前面，维数是向量中的元素个数；而在这里，维数是数组的索引个数。一个一维，或者说1-D的数组，有一个索引。在课程 1，我们会使用NumPy的1-D数组来表示向量。
- 1-D array，shape (n,): 包含n个元素，索引从[0]到[n-1]
 

<a name="toc_40015_3.3"></a>
## 3.3 Vector Creation创建数组


Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.

创建NumPy的数据，第一个要提供的参数通常是对象的shape(形状)，shape可以是单个值，对应1-D对象，也可以是个元组(tuple)，类似(n, m, ...)，指定对象的形状。下面是一个创建向量的例子。

In [2]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.3462114  0.60932422 0.49491658 0.65983355], a shape = (4,), a data type = float64


Some data creation routines do not take a shape tuple:
不使用shape元组的创建数据的方法

In [3]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.81979029 0.58625349 0.9627486  0.33449045], a shape = (4,), a data type = float64


values can be specified manually as well. 
数组内的值也可以手动输入

In [4]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


These have all created a one-dimensional vector  `a` with four elements. `a.shape` returns the dimensions. Here we see a.shape = `(4,)` indicating a 1-d array with 4 elements.  
以上是所有创建有4个元素的一维向量`a`的方法。你可以使用`a.shape`获取向量的维数。在上面的测试中我们可以看到，含有4个元素的一维向量的shape为(4,)

<a name="toc_40015_3.4"></a>
## 3.4 Operations on Vectors 向量操作
Let's explore some operations using vectors.

让我们研究一些对向量的操作
<a name="toc_40015_3.4.1"></a>
### 3.4.1 Indexing 索引
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We will explore only the basics needed for the course here. Reference [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) for more details.  
**Indexing** means referring to *an element* of an array by its position within the array.  
**Slicing** means getting a *subset* of elements from an array based on their indices.  
NumPy starts indexing at zero so the 3rd element of an vector $\mathbf{a}$ is `a[2]`.

向量中的元素可以通过索引和切片访问。NumPy提供了完备的索引和切片功能。我们只需要研究可能所需要的部分。你可以参考[Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) 来进一步学习。

**索引**是指通过在数组中的位置，选择数组中的**一个元素**

**切片**是指获取数组的一个**子集**
NumPy的索引从0开始，因此向量$\mathbf{a}$中的第3个元素为`a[2]`

In [5]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexs count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 Slicing 切片
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

切片使用三个参数(`start:stop:step`)来获取数组的一个子集。也可以缺省部分参数，学习这部分的最好方法是通过举例：（主要注意[start,stop)左包含右不包含。）

In [6]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 Single vector operations 单变量操作
There are a number of useful operations that involve operations on a single vector.

下面是一些有用的针对单变量的操作

In [7]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 Vector Vector element-wise operations 向量与向量 逐元素的操作
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

大多数的NumPy运算，包括逻辑运算符与比较运算符。这些运算是逐元素进行的。例如
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

In [8]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


Of course, for this to work correctly, the vectors must be of the same size:

当然，为了确保正确运行，两个向量的大小应该一致

In [9]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 Scalar Vector operations 倍乘操作
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

向量可以被倍乘一个数字，这个倍数是个标量。倍乘作用于向量的每个元素上。

In [10]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 Vector Vector dot product 向量点乘
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

点乘是线性代数和NumPy的重点。该操作在本课程中非常常见，且应该被深刻理解。点乘的有关内容见下。

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800> 

The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same. 

点乘将两个向量的值逐个相乘，然后求和。
向量点乘需要两个向量的维度相同。

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

让我们在下面自己实现一个点乘：

**使用for循环**， 实现一个返回两个向量点乘结果的函数。函数的定义如下：
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
假定`a`和`b`的维数相同

In [11]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [12]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


Note, the dot product is expected to return a scalar value. 

Let's try the same operations using `np.dot`.  

注意，点乘应该返回一个标量。

让我们使用`np.dot`来尝试同样的计算。

In [13]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


Above, you will note that the results for 1-D matched our implementation.

综上，你可以看出来结果和我们的实现一致。
（在这里提醒一下，从交换点乘顺序，结果相同可以看出，点乘满足交换律，深入理解为什么满足交换律可以去看3b1b的《线性代数的本质》）

<a name="toc_40015_3.4.7"></a>
### 3.4.7 The Need for Speed: vector vs for loop 效率比拼
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

我们应当使用NumPy库实现的点乘，因为该实现效率更高。解释如下：

In [14]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 7.8020 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 1178.4315 ms 


So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

可见，向量化能够极大程度提升效率。因为NumPy允许在底层硬件上并行处理数据。GPU和现代CPU的**单指令，多数据(Single Instruction，Multiple Data, SIMD)管线**允许并行处理多个操作。由于机器学习的数据集通常都很大，这点非常重要。

<a name="toc_12345_3.4.8"></a>
### 3.4.8 Vector Vector operations in Course 1 
### 3.4.8 课程1中的向量运算
Vector Vector operations will appear frequently in course 1. Here is why:
- Going forward, our examples will be stored in an array, `X_train` of dimension (m,n). This will be explained more in context, but here it is important to note it is a 2 Dimensional array or matrix (see next section on matrices).
- `w` will be a 1-dimensional vector of shape (n,).
- we will perform operations by looping through the examples, extracting each example to work on individually by indexing X. For example:`X[i]`
- `X[i]` returns a value of shape (n,), a 1-dimensional vector. Consequently, operations involving `X[i]` are often vector-vector.  

That is a somewhat lengthy explanation, but aligning and understanding the shapes of your operands is important when performing vector operations.

向量运算将在课程1中频繁出现，原因如下：
- 在后面，我们的样例将会是存储在数组中，维度为(m,n)的`X_train`。这样可以描述更多的内容，但需要注意，这是一个2维的数组，或者称矩阵（详见下一小节）
- `w`将会是1维的向量，shape(n,)
- 我们需要循环遍历样例来进行预处理（preform），通过索引提取出X的每个样例并单独处理，例如`X[i]`
- `X[i]`返回shape(n,)的值，这是一个1维向量。总之，包含`X[i]`的操作通常都是向量-向量操作

这段话有些长篇大论，但理解并让数据的shape一致是预处理向量操作中的重点。

In [15]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 Matrices 矩阵


<a name="toc_40015_4.1"></a>
## 4.1 Abstract 摘要
Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.  
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> Generic Matrix Notation, 1st index is row, 2nd is column </figcaption>
<figure/>
        
 矩阵是2维的数组。矩阵中的元素类型一致。习惯上，矩阵用大写加粗英文字母表示，例如$\mathbf{X}$。在本lab和其他lab中，`m`通常定义为矩阵的行数，`n`定义为矩阵的列数。矩阵中的元素可以使用2维索引访问。在数学上，索引从1到n；而在计算机科学中，索引从0到n-1。

<a name="toc_40015_4.2"></a>
## 4.2 NumPy Arrays NumPy数组

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). These were described earlier. Matrices have a two-dimensional (2-D) index [m,n].

In Course 1, 2-D matrices are used to hold training data. Training data is $m$ examples by $n$ features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review: 
- data creation
- slicing and indexing

正如前面提到的，NumPy的基本数据结构是一个可索引的n维数组，包含具有相同类型(`dtype`)的元素。矩阵的索引为2D，记为[m,n]

在课程1中。2D矩阵用于存储训练数据。训练数据有$m$个样例，$n$个特征值，组成(m,n)大小的矩阵。课程以不会直接对矩阵进行操作，而是提取出矩阵中的一个个样例，作为向量并处理。之后你会复习到：
- 数据创建
- 索引和切片

<a name="toc_40015_4.3"></a>
## 4.3 Matrix Creation 矩阵创建
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples

创建1D向量的方法也可以用于创建2D或nD数组。下面是一些例子。

Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.

如下，shape元组指定了2D的形状。注意numpy使用括号来表示每个维度。更进一步，当输出的时候，每行输出数组的一行。

In [2]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.04199024]]


One can also manually specify data. Dimensions are specified with additional brackets matching the format in the printing above.

你同样可以手动输入信息。通过类似上面输出的方括号格式来组织数据。

In [3]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 Operations on Matrices 矩阵操作
Let's explore some operations using matrices.

让我们研究一下矩阵的一些操作

<a name="toc_40015_4.4.1"></a>
### 4.4.1 Indexing 索引


Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

矩阵有第二个索引，两个索引分别表示[行，列]。既可以访问矩阵中的一个元素，也可以访问矩阵中的某行/列，如下：

In [4]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


It is worth drawing attention to the last example. Accessing a matrix by just specifying the row will return a *1-D vector*.

请注意最后一个测试样例。只指定行来访问矩阵会返回一个1D向量

**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.

前面的样例使用了`.reshape`方法[reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)来修改数组的形状。
`a = np.arange(6).reshape(-1, 2) `  
这行代码首先创建一个1D向量，包含6个元组。接着使用reshape命令，将向量的形状修改为2D数组，也可以写为：
`a = np.arange(6).reshape(3, 2) `
同样可以获得一个3行2列的数组。
参数-1使得程序使用给定的数组大小和列数计算被缺省的行数


<a name="toc_40015_4.4.2"></a>
### 4.4.2 Slicing 切片
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

使用(`start:stop:step`)的集合来创建数组的切片。只包含值的切片也是可行的。最好的理解方式就是通过样例：

In [5]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## Congratulations! 
In this lab you mastered the features of Python and NumPy that are needed for Course 1.

在这个lab中，你掌握了课程1中所需的Python和NumPy功能。